services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - path: .env
        required: true
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      devops_mynetwork:
        ipv4_address: 172.21.0.2
    restart: unless-stopped

volumes:
  pg_data:
    driver: local

networks:
  devops_mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
