"""Auto-generated migration

Revision ID: 2955da7260c4
Revises: dac4dff09ec9
Create Date: 2025-09-29 22:59:26.968510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2955da7260c4'
down_revision: Union[str, Sequence[str], None] = 'dac4dff09ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesselement',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accessrule',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('businesselement_id', sa.UUID(), nullable=False),
    sa.Column('read_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_all_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('create_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('update_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('update_all_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('delete_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('delete_all_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['businesselement_id'], ['businesselement.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'businesselement_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessrule')
    op.drop_table('businesselement')
    # ### end Alembic commands ###
