"""uto-generated migration

Revision ID: 557efc557696
Revises: 6e1ae2a1f2f7
Create Date: 2025-10-24 21:10:07.231824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557efc557696'
down_revision: Union[str, Sequence[str], None] = '6e1ae2a1f2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_role', 'userrole', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'userrole', type_='unique')
    # ### end Alembic commands ###
