"""Auto-generated migration

Revision ID: 877f5c2fd022
Revises: b30f10c59d00
Create Date: 2025-10-18 23:43:25.046645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877f5c2fd022'
down_revision: Union[str, Sequence[str], None] = 'b30f10c59d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fileupload', 'mime_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileupload', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
