"""Auto-generated migration

Revision ID: d021dc1b002b
Revises: fca4cf2c0aa0
Create Date: 2025-10-03 13:23:25.219555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd021dc1b002b'
down_revision: Union[str, Sequence[str], None] = 'fca4cf2c0aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'created_at')
    # ### end Alembic commands ###
